apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: zeebe-cmd
  namespace: zeebe-token-repro
spec:
  type: bindings.zeebe.command
  version: v1
  metadata:
    - name: gatewayAddr
      value: "zeebe-mock:26500"
    - name: usePlainTextConnection
      value: "true"
